---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: flask-app
data:
  mysql-password: "ZGV2b3BzCg=="
  mysql-root-password: "bXktc2VjcmV0LXB3Cg=="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: flask-app
data:
  mysql-db-name: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: flask-app
  labels:
    name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
  namespace: flask-app
spec:
  containers:
    - name: mysql
      image: mysql:8
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 200m
          memory: 512Mi
      env:
        - name: "MYSQL_USER"
          value: devops
        - name: "MYSQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: "MYSQL_DATABASE"
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-db-name
        - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
      ports:
        - containerPort: 3306
          name: mysql-container
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim: 
        claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels: 
    name: mysql
  namespace: flask-app
  spec:
    selector:
      name: mysql
    ports:
      - protocol: TCP
        port: 3306
        targetPort: mysql-container
        name: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    name: mysql
  namespace: flask-app
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        image: k8s.gcr.io/mysql:8
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
      name: mysql
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
